<a href="https://colab.research.google.com/github/fjdvm/skin-disease-classifier/blob/main/skin_disease_classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import torch
import torchvision
import pandas as pd
import numpy as np
from PIL import Image

In [11]:
print(torch.cuda.is_available())

True

In [12]:
from google.colab import userdata
import os

token = userdata.get('KAGGLE_TOKEN')

os.makedirs(os.path.expanduser("~/.kaggle"), exist_ok=True)
with open(os.path.expanduser("~/.kaggle/access_token"), "w") as f:
  f.write(token)
os.chmod(os.path.expanduser("~/.kaggle/access_token"), 0o600)

*Skin Cancer MNIST: HAM10000*

https://www.kaggle.com/datasets/kmader/skin-cancer-mnist-ham10000

In [17]:
!kaggle datasets download -d kmader/skin-cancer-mnist-ham10000
!unzip -q skin-https://www.kaggle.com/datasets/kmader/skin-cancer-mnist-ham10000cancer-mnist-ham10000.zip -d ham10000_data
!ls ham10000_data

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
Dataset URL: https://www.kaggle.com/datasets/kmader/skin-cancer-mnist-ham10000
License(s): CC-BY-NC-SA-4.0
skin-cancer-mnist-ham10000.zip: Skipping, found more recently modified local copy (use --force to force download)
unzip:  cannot find or open skin-https://www.kaggle.com/datasets/kmader/skin-cancer-mnist-ham10000cancer-mnist-ham10000.zip, skin-https://www.kaggle.com/datasets/kmader/skin-cancer-mnist-ham10000cancer-mnist-ham10000.zip.zip or skin-https://www.kaggle.com/datasets/kmader/skin-cancer-mnist-ham10000cancer-mnist-ham10000.zip.ZIP.
ham10000_images_part_1	HAM10000_images_part_2	hmnist_28_28_RGB.csv
HAM10000_images_part_1	HAM10000_metadata.csv	hmnist_8_8_L.csv
ham10000_images_part_2	hmnist_28_28_L.csv	hmnist_8_8_RGB.csv

In [20]:
df = pd.read_csv("ham10000_data/HAM10000_metadata.csv")
print(df.shape)
df.head()

df['dx'].value_counts()

(10015, 7)

dx
nv       6705
mel      1113
bkl      1099
bcc       514
akiec     327
vasc      142
df        115
Name: count, dtype: int64

In [22]:
df['lesion_id'].value_counts().head()

lesion_id
HAM_0003789    6
HAM_0005263    6
HAM_0000835    6
HAM_0001863    6
HAM_0000893    5
Name: count, dtype: int64